//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtqanArchive.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Administration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Administration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtqanArchive.Localization.Resources.Administration", typeof(Administration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ticket transaction failed.
        /// </summary>
        public static string AddTicketTransactionFailed {
            get {
                return ResourceManager.GetString("AddTicketTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a financial account with the same payment method.
        /// </summary>
        public static string AlreadyHaveFinancialAccountWithSamePaymentMethod {
            get {
                return ResourceManager.GetString("AlreadyHaveFinancialAccountWithSamePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a portfolio with the same currency.
        /// </summary>
        public static string AlreadyHavePortfolioWithSameCurrency {
            get {
                return ResourceManager.GetString("AlreadyHavePortfolioWithSameCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a booked ticket.
        /// </summary>
        public static string CannotDeleteBookedTicket {
            get {
                return ResourceManager.GetString("CannotDeleteBookedTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete default portfolio.
        /// </summary>
        public static string CannotDeleteDefaultPortfolio {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change event status failed.
        /// </summary>
        public static string ChangedStatusFailed {
            get {
                return ResourceManager.GetString("ChangedStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed  status successfully.
        /// </summary>
        public static string ChangedStatusSuccessfully {
            get {
                return ResourceManager.GetString("ChangedStatusSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update portfolio.
        /// </summary>
        public static string CouldNotUpdatePortfolio {
            get {
                return ResourceManager.GetString("CouldNotUpdatePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer following failed.
        /// </summary>
        public static string CustomerFollowingFailed {
            get {
                return ResourceManager.GetString("CustomerFollowingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer unfollowing failed.
        /// </summary>
        public static string CustomerUnfollowingFailed {
            get {
                return ResourceManager.GetString("CustomerUnfollowingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event already approved.
        /// </summary>
        public static string EventAlreadyApproved {
            get {
                return ResourceManager.GetString("EventAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event has been approved.
        /// </summary>
        public static string EventApproved {
            get {
                return ResourceManager.GetString("EventApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event approved successfully.
        /// </summary>
        public static string EventApprovedSuccessfully {
            get {
                return ResourceManager.GetString("EventApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change event status failed.
        /// </summary>
        public static string EventChangeStatusFailed {
            get {
                return ResourceManager.GetString("EventChangeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Changed status successfully.
        /// </summary>
        public static string EventChangeStatusSuccessfully {
            get {
                return ResourceManager.GetString("EventChangeStatusSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event current status not allow to edit.
        /// </summary>
        public static string EventEditNotAllow {
            get {
                return ResourceManager.GetString("EventEditNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has the same status.
        /// </summary>
        public static string EventHasSameStatus {
            get {
                return ResourceManager.GetString("EventHasSameStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event media not found.
        /// </summary>
        public static string EventMediaNotFound {
            get {
                return ResourceManager.GetString("EventMediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event is open for booking now.
        /// </summary>
        public static string EventOpenForBooking {
            get {
                return ResourceManager.GetString("EventOpenForBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events not found.
        /// </summary>
        public static string EventsNotFound {
            get {
                return ResourceManager.GetString("EventsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate seat.
        /// </summary>
        public static string FailedToActivateSeat {
            get {
                return ResourceManager.GetString("FailedToActivateSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deactivate seat.
        /// </summary>
        public static string FailedToDeactivateSeat {
            get {
                return ResourceManager.GetString("FailedToDeactivateSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update portfolio.
        /// </summary>
        public static string FailedToUpdatePortfolio {
            get {
                return ResourceManager.GetString("FailedToUpdatePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category to user favorites failed.
        /// </summary>
        public static string FavoriteCategoryAddCategoryFailed {
            get {
                return ResourceManager.GetString("FavoriteCategoryAddCategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category from user favorites failed.
        /// </summary>
        public static string FavoriteCategoryRemoveCategoryFailed {
            get {
                return ResourceManager.GetString("FavoriteCategoryRemoveCategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor plan is not found.
        /// </summary>
        public static string FloorPlanNotFound {
            get {
                return ResourceManager.GetString("FloorPlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string HomeEventSection_Favorite {
            get {
                return ResourceManager.GetString("HomeEventSection_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following customer.
        /// </summary>
        public static string HomeEventSection_FollowingCustomer {
            get {
                return ResourceManager.GetString("HomeEventSection_FollowingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string HomeEventSection_Free {
            get {
                return ResourceManager.GetString("HomeEventSection_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest events.
        /// </summary>
        public static string HomeEventSection_NearestEvent {
            get {
                return ResourceManager.GetString("HomeEventSection_NearestEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string HomeEventSection_Popular {
            get {
                return ResourceManager.GetString("HomeEventSection_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        public static string HomeEventSection_Recommend {
            get {
                return ResourceManager.GetString("HomeEventSection_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        public static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image content type.
        /// </summary>
        public static string InvalidImageContentType {
            get {
                return ResourceManager.GetString("InvalidImageContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image path.
        /// </summary>
        public static string InvalidImagePath {
            get {
                return ResourceManager.GetString("InvalidImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media content type.
        /// </summary>
        public static string InvalidMediaContentType {
            get {
                return ResourceManager.GetString("InvalidMediaContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media path.
        /// </summary>
        public static string InvalidMediaPath {
            get {
                return ResourceManager.GetString("InvalidMediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has invalid characters.
        /// </summary>
        public static string MessageHasInvalidCharacters {
            get {
                return ResourceManager.GetString("MessageHasInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has the same status.
        /// </summary>
        public static string MessageHasSameStatus {
            get {
                return ResourceManager.GetString("MessageHasSameStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not Found.
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one financial account.
        /// </summary>
        public static string MustHaveOneFinancialAccount {
            get {
                return ResourceManager.GetString("MustHaveOneFinancialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tickets available.
        /// </summary>
        public static string NewTicketsAvailable {
            get {
                return ResourceManager.GetString("NewTicketsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio is already set as default.
        /// </summary>
        public static string PortfolioAlreadyDefault {
            get {
                return ResourceManager.GetString("PortfolioAlreadyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio is blocked.
        /// </summary>
        public static string PortfolioBlocked {
            get {
                return ResourceManager.GetString("PortfolioBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio not found.
        /// </summary>
        public static string PortfolioNotFound {
            get {
                return ResourceManager.GetString("PortfolioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio update failed.
        /// </summary>
        public static string PortfolioUpdateFailed {
            get {
                return ResourceManager.GetString("PortfolioUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat is already activated.
        /// </summary>
        public static string SeatAlreadyActivated {
            get {
                return ResourceManager.GetString("SeatAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat is already deactivated.
        /// </summary>
        public static string SeatAlreadyDeactivated {
            get {
                return ResourceManager.GetString("SeatAlreadyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat not found.
        /// </summary>
        public static string SeatNotFound {
            get {
                return ResourceManager.GetString("SeatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket change status failed.
        /// </summary>
        public static string TicketChangeStatusFailed {
            get {
                return ResourceManager.GetString("TicketChangeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket change status successfully.
        /// </summary>
        public static string TicketChangeStatusSuccessfully {
            get {
                return ResourceManager.GetString("TicketChangeStatusSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket class not found.
        /// </summary>
        public static string TicketClassNotFound {
            get {
                return ResourceManager.GetString("TicketClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket insert failed.
        /// </summary>
        public static string TicketInsertFailed {
            get {
                return ResourceManager.GetString("TicketInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found.
        /// </summary>
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets not found.
        /// </summary>
        public static string TicketsNotFound {
            get {
                return ResourceManager.GetString("TicketsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets update failed.
        /// </summary>
        public static string TicketsUpdateFailed {
            get {
                return ResourceManager.GetString("TicketsUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction change status failed.
        /// </summary>
        public static string TransactionChangeStatusFailed {
            get {
                return ResourceManager.GetString("TransactionChangeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction insert failed.
        /// </summary>
        public static string TransactionInsertFailed {
            get {
                return ResourceManager.GetString("TransactionInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions update failed.
        /// </summary>
        public static string TransactionsUpdateFailed {
            get {
                return ResourceManager.GetString("TransactionsUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update customer portfolio failed.
        /// </summary>
        public static string UpdateCustomerPortfolioFailed {
            get {
                return ResourceManager.GetString("UpdateCustomerPortfolioFailed", resourceCulture);
            }
        }
    }
}
