//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtqanArchive.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtqanArchive.Localization.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Deny.
        /// </summary>
        public static string AccessDeny {
            get {
                return ResourceManager.GetString("AccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be active, please check your data and try again.
        /// </summary>
        public static string AlertActiveErrorMessage {
            get {
                return ResourceManager.GetString("AlertActiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been activated.
        /// </summary>
        public static string AlertActiveInfoMessage {
            get {
                return ResourceManager.GetString("AlertActiveInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been activated.
        /// </summary>
        public static string AlertActiveSuccessMessage {
            get {
                return ResourceManager.GetString("AlertActiveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be active.
        /// </summary>
        public static string AlertActiveWarningMessage {
            get {
                return ResourceManager.GetString("AlertActiveWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be added, please check your data and try again.
        /// </summary>
        public static string AlertAddErrorMessage {
            get {
                return ResourceManager.GetString("AlertAddErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been added.
        /// </summary>
        public static string AlertAddInfoMessage {
            get {
                return ResourceManager.GetString("AlertAddInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been added.
        /// </summary>
        public static string AlertAddSuccessMessage {
            get {
                return ResourceManager.GetString("AlertAddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be add.
        /// </summary>
        public static string AlertAddWarningMessage {
            get {
                return ResourceManager.GetString("AlertAddWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be deactive, please check your data and try again.
        /// </summary>
        public static string AlertDeactiveErrorMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deactivated.
        /// </summary>
        public static string AlertDeactiveInfoMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deatctivated.
        /// </summary>
        public static string AlertDeactiveSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be deactive.
        /// </summary>
        public static string AlertDeactiveWarningMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be delete, please check your data and try again.
        /// </summary>
        public static string AlertDeleteErrorMessage {
            get {
                return ResourceManager.GetString("AlertDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be delete forever, please check your data and try again.
        /// </summary>
        public static string AlertDeleteForeverErrorMessage {
            get {
                return ResourceManager.GetString("AlertDeleteForeverErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted forever.
        /// </summary>
        public static string AlertDeleteForeverInfoMessage {
            get {
                return ResourceManager.GetString("AlertDeleteForeverInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted forever.
        /// </summary>
        public static string AlertDeleteForeverSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeleteForeverSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be delete forever.
        /// </summary>
        public static string AlertDeleteForeverWarningMessage {
            get {
                return ResourceManager.GetString("AlertDeleteForeverWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted.
        /// </summary>
        public static string AlertDeleteInfoMessage {
            get {
                return ResourceManager.GetString("AlertDeleteInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted.
        /// </summary>
        public static string AlertDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be delete.
        /// </summary>
        public static string AlertDeleteWarningMessage {
            get {
                return ResourceManager.GetString("AlertDeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be update, please check your data and try again.
        /// </summary>
        public static string AlertEditErrorMessage {
            get {
                return ResourceManager.GetString("AlertEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been updated.
        /// </summary>
        public static string AlertEditInfoMessage {
            get {
                return ResourceManager.GetString("AlertEditInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been updated.
        /// </summary>
        public static string AlertEditSuccessMessage {
            get {
                return ResourceManager.GetString("AlertEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be update.
        /// </summary>
        public static string AlertEditWarningMessage {
            get {
                return ResourceManager.GetString("AlertEditWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be export, please try again.
        /// </summary>
        public static string AlertExportErrorMessage {
            get {
                return ResourceManager.GetString("AlertExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been exported.
        /// </summary>
        public static string AlertExportInfoMessage {
            get {
                return ResourceManager.GetString("AlertExportInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been exported.
        /// </summary>
        public static string AlertExportSuccessMessage {
            get {
                return ResourceManager.GetString("AlertExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be export.
        /// </summary>
        public static string AlertExportWarningMessage {
            get {
                return ResourceManager.GetString("AlertExportWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be import, please check your data and try again.
        /// </summary>
        public static string AlertImportErrorMessage {
            get {
                return ResourceManager.GetString("AlertImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been imported.
        /// </summary>
        public static string AlertImportInfoMessage {
            get {
                return ResourceManager.GetString("AlertImportInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been imported.
        /// </summary>
        public static string AlertImportSuccessMessage {
            get {
                return ResourceManager.GetString("AlertImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be import.
        /// </summary>
        public static string AlertImportWarningMessage {
            get {
                return ResourceManager.GetString("AlertImportWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info!.
        /// </summary>
        public static string AlertInfo {
            get {
                return ResourceManager.GetString("AlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be restore, please check your data and try again.
        /// </summary>
        public static string AlertRestoreErrorMessage {
            get {
                return ResourceManager.GetString("AlertRestoreErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been restored.
        /// </summary>
        public static string AlertRestoreInfoMessage {
            get {
                return ResourceManager.GetString("AlertRestoreInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been restored.
        /// </summary>
        public static string AlertRestoreSuccessMessage {
            get {
                return ResourceManager.GetString("AlertRestoreSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be restore.
        /// </summary>
        public static string AlertRestoreWarningMessage {
            get {
                return ResourceManager.GetString("AlertRestoreWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string AlertWarning {
            get {
                return ResourceManager.GetString("AlertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Block selected item(s)?.
        /// </summary>
        public static string BlockConfirmDialogBody {
            get {
                return ResourceManager.GetString("BlockConfirmDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Confirm.
        /// </summary>
        public static string BlockConfirmDialogHeader {
            get {
                return ResourceManager.GetString("BlockConfirmDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access deny because the model has been blocked..
        /// </summary>
        public static string BlockedViewModelContent {
            get {
                return ResourceManager.GetString("BlockedViewModelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Model.
        /// </summary>
        public static string BlockedViewModelMsg {
            get {
                return ResourceManager.GetString("BlockedViewModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Notification.
        /// </summary>
        public static string BlockNotification {
            get {
                return ResourceManager.GetString("BlockNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ButtonApprove {
            get {
                return ResourceManager.GetString("ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string ButtonAssign {
            get {
                return ResourceManager.GetString("ButtonAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string ButtonBlock {
            get {
                return ResourceManager.GetString("ButtonBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report (Complete).
        /// </summary>
        public static string ButtonCompleteReport {
            get {
                return ResourceManager.GetString("ButtonCompleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-active.
        /// </summary>
        public static string ButtonDeactive {
            get {
                return ResourceManager.GetString("ButtonDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string ButtonFinish {
            get {
                return ResourceManager.GetString("ButtonFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ButtonHistory {
            get {
                return ResourceManager.GetString("ButtonHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string ButtonPreviousShortCut {
            get {
                return ResourceManager.GetString("ButtonPreviousShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string ButtonSaveAndClose {
            get {
                return ResourceManager.GetString("ButtonSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save?.
        /// </summary>
        public static string ConfirmSaveContent {
            get {
                return ResourceManager.GetString("ConfirmSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the save.
        /// </summary>
        public static string ConfirmSaveTitle {
            get {
                return ResourceManager.GetString("ConfirmSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went wrong. please try again later.
        /// </summary>
        public static string ConflictDataErrorMessage {
            get {
                return ResourceManager.GetString("ConflictDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create on.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery request has already delivery note. can not create delivery note.
        /// </summary>
        public static string CreateExistDeliveryNoteErrorMsgContent {
            get {
                return ResourceManager.GetString("CreateExistDeliveryNoteErrorMsgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by.
        /// </summary>
        public static string CreateUserFullNameEn {
            get {
                return ResourceManager.GetString("CreateUserFullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DeactivateConfirmActionButton {
            get {
                return ResourceManager.GetString("DeactivateConfirmActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeactivateConfirmCloseButton {
            get {
                return ResourceManager.GetString("DeactivateConfirmCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to deactivate selected item(s)?.
        /// </summary>
        public static string DeactivateConfirmDialogBody {
            get {
                return ResourceManager.GetString("DeactivateConfirmDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Confirm.
        /// </summary>
        public static string DeactivateConfirmDialogHeader {
            get {
                return ResourceManager.GetString("DeactivateConfirmDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DeleteConfirmActionButton {
            get {
                return ResourceManager.GetString("DeleteConfirmActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeleteConfirmCloseButton {
            get {
                return ResourceManager.GetString("DeleteConfirmCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected item(s)?.
        /// </summary>
        public static string DeleteConfirmDialogBody {
            get {
                return ResourceManager.GetString("DeleteConfirmDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string DeleteConfirmDialogHeader {
            get {
                return ResourceManager.GetString("DeleteConfirmDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: you can not delete saved item.
        /// </summary>
        public static string DeleteSavedItemErrorMsg {
            get {
                return ResourceManager.GetString("DeleteSavedItemErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note item has no serila. please review your data.
        /// </summary>
        public static string DeliveryNoteItemHasNoSerialError {
            get {
                return ResourceManager.GetString("DeliveryNoteItemHasNoSerialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        public static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Is Empty.
        /// </summary>
        public static string EmptyFileErrorMessage {
            get {
                return ResourceManager.GetString("EmptyFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string ErrorMsg_FileNotFound {
            get {
                return ResourceManager.GetString("ErrorMsg_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild parameters.
        /// </summary>
        public static string ErrorMsg_InvaildParameters {
            get {
                return ResourceManager.GetString("ErrorMsg_InvaildParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) not found.
        /// </summary>
        public static string ErrorMsg_ItemNotFound {
            get {
                return ResourceManager.GetString("ErrorMsg_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image failed.
        /// </summary>
        public static string ErrorMsg_SaveImageFailed {
            get {
                return ResourceManager.GetString("ErrorMsg_SaveImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string ErrorMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("ErrorMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved failed.
        /// </summary>
        public static string FileSavedFailed {
            get {
                return ResourceManager.GetString("FileSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Have Been Uploaded.
        /// </summary>
        public static string FilesHaveBeenUploaded {
            get {
                return ResourceManager.GetString("FilesHaveBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Failed.
        /// </summary>
        public static string FileUploadedFailed {
            get {
                return ResourceManager.GetString("FileUploadedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded successfully.
        /// </summary>
        public static string FileUploadedsuccessfully {
            get {
                return ResourceManager.GetString("FileUploadedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Create Date.
        /// </summary>
        public static string FromCreateDate {
            get {
                return ResourceManager.GetString("FromCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (#itemCount) items imported successfully.
        /// </summary>
        public static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import To Fill Data.
        /// </summary>
        public static string ImportToFillData {
            get {
                return ResourceManager.GetString("ImportToFillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import To Find.
        /// </summary>
        public static string ImportToFind {
            get {
                return ResourceManager.GetString("ImportToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import To Replace.
        /// </summary>
        public static string ImportToReplace {
            get {
                return ResourceManager.GetString("ImportToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import To Update.
        /// </summary>
        public static string ImportToUpdate {
            get {
                return ResourceManager.GetString("ImportToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Update File.
        /// </summary>
        public static string ImportUpdateFile {
            get {
                return ResourceManager.GetString("ImportUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string IsBlock {
            get {
                return ResourceManager.GetString("IsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string IsCorrect {
            get {
                return ResourceManager.GetString("IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) updated successfully.
        /// </summary>
        public static string ItemsUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("ItemsUpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading please wait.....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify on.
        /// </summary>
        public static string ModifyDateTime {
            get {
                return ResourceManager.GetString("ModifyDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify by .
        /// </summary>
        public static string ModifyUserFullNameEn {
            get {
                return ResourceManager.GetString("ModifyUserFullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Matched.
        /// </summary>
        public static string NoDataMatched {
            get {
                return ResourceManager.GetString("NoDataMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Has Been Uploaded.
        /// </summary>
        public static string NoFileHasBeenUploaded {
            get {
                return ResourceManager.GetString("NoFileHasBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access deny because item is not exist..
        /// </summary>
        public static string NotExistViewModelContent {
            get {
                return ResourceManager.GetString("NotExistViewModelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Exist.
        /// </summary>
        public static string NotExistViewModelMsg {
            get {
                return ResourceManager.GetString("NotExistViewModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Is Null.
        /// </summary>
        public static string NullFileErrorMessage {
            get {
                return ResourceManager.GetString("NullFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Note.
        /// </summary>
        public static string OtherNote {
            get {
                return ResourceManager.GetString("OtherNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Create.
        /// </summary>
        public static string QuickCreate {
            get {
                return ResourceManager.GetString("QuickCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved successfully.
        /// </summary>
        public static string SaveImageSuccessfully {
            get {
                return ResourceManager.GetString("SaveImageSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- All ----.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Select ----.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up With Email.
        /// </summary>
        public static string SignUpWithEmail {
            get {
                return ResourceManager.GetString("SignUpWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Create Date.
        /// </summary>
        public static string ToCreateDate {
            get {
                return ResourceManager.GetString("ToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type isn&apos;t exist.
        /// </summary>
        public static string TypeNotExist {
            get {
                return ResourceManager.GetString("TypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to access a system process for which you are not authorized..
        /// </summary>
        public static string UnauthorizedContent {
            get {
                return ResourceManager.GetString("UnauthorizedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!.
        /// </summary>
        public static string UnauthorizedMsg {
            get {
                return ResourceManager.GetString("UnauthorizedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access or view the model in current status..
        /// </summary>
        public static string UnAuthourizedViewModelContent {
            get {
                return ResourceManager.GetString("UnAuthourizedViewModelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!.
        /// </summary>
        public static string UnAuthourizedViewModelMsg {
            get {
                return ResourceManager.GetString("UnAuthourizedViewModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Date.
        /// </summary>
        public static string UntilDate {
            get {
                return ResourceManager.GetString("UntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access deny because the model has been Upgraded to (#status)..
        /// </summary>
        public static string UpgradeViewModelContent {
            get {
                return ResourceManager.GetString("UpgradeViewModelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Upgraded.
        /// </summary>
        public static string UpgradeViewModelMsg {
            get {
                return ResourceManager.GetString("UpgradeViewModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
    }
}
