//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtqanArchive.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtqanArchive.Localization.Resources.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your available balance has been transfered to your financial account.
        /// </summary>
        public static string AvaialbleBalanceTransfered {
            get {
                return ResourceManager.GetString("AvaialbleBalanceTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance transfer complete.
        /// </summary>
        public static string BalanceTransferComplete {
            get {
                return ResourceManager.GetString("BalanceTransferComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block user denied.
        /// </summary>
        public static string BlockUserDenied {
            get {
                return ResourceManager.GetString("BlockUserDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email sent failed.
        /// </summary>
        public static string ConfirmationEmailSentFailed {
            get {
                return ResourceManager.GetString("ConfirmationEmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Email sent successfully.
        /// </summary>
        public static string ConfirmationEmailSentSuccessfully {
            get {
                return ResourceManager.GetString("ConfirmationEmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user denied.
        /// </summary>
        public static string DeleteUserDenied {
            get {
                return ResourceManager.GetString("DeleteUserDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed Successfully.
        /// </summary>
        public static string EmailConfirmedSuccessMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        public static string EmailSendFailed {
            get {
                return ResourceManager.GetString("EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ErrorMsg_InvalidPasswordLength {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created the maximum number of employee users.
        /// </summary>
        public static string ErrorMsg_MaxNoCustomerEmployeeUsers {
            get {
                return ResourceManager.GetString("ErrorMsg_MaxNoCustomerEmployeeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string ErrorMsg_UserNotFound {
            get {
                return ResourceManager.GetString("ErrorMsg_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login provider remote error.
        /// </summary>
        public static string ExternalLoginProviderRemoteError {
            get {
                return ResourceManager.GetString("ExternalLoginProviderRemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete token.
        /// </summary>
        public static string FailedToDeleteToken {
            get {
                return ResourceManager.GetString("FailedToDeleteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save passowrd token.
        /// </summary>
        public static string FailedToSavePassowrdToken {
            get {
                return ResourceManager.GetString("FailedToSavePassowrdToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save token.
        /// </summary>
        public static string FailedToSaveToken {
            get {
                return ResourceManager.GetString("FailedToSaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading external login information failed.
        /// </summary>
        public static string LoadingExternalLoginInformationFailed {
            get {
                return ResourceManager.GetString("LoadingExternalLoginInformationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP Email Failed.
        /// </summary>
        public static string OTPEmailSentFailed {
            get {
                return ResourceManager.GetString("OTPEmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Email sent successfully.
        /// </summary>
        public static string OTPEmailSentSuccessfully {
            get {
                return ResourceManager.GetString("OTPEmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password.
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully!.
        /// </summary>
        public static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during payment. please contact customer service.
        /// </summary>
        public static string PaymentProcessException {
            get {
                return ResourceManager.GetString("PaymentProcessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email sent failed.
        /// </summary>
        public static string ResetPasswordEmailSentFailed {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email sent successfully.
        /// </summary>
        public static string ResetPasswordEmailSentSuccessfully {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token aready exists.
        /// </summary>
        public static string TokenAlreadyExists {
            get {
                return ResourceManager.GetString("TokenAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token deleted successfully.
        /// </summary>
        public static string TokenDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TokenDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not exist.
        /// </summary>
        public static string TokenDoesNotExist {
            get {
                return ResourceManager.GetString("TokenDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is already expired.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account locked out..
        /// </summary>
        public static string UserAccountLockedOut {
            get {
                return ResourceManager.GetString("UserAccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created failed.
        /// </summary>
        public static string UserCreatedFailed {
            get {
                return ResourceManager.GetString("UserCreatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login denied.
        /// </summary>
        public static string UserLoginDenied {
            get {
                return ResourceManager.GetString("UserLoginDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User register completed successfully.
        /// </summary>
        public static string UserRegisterCompletedSuccessfully {
            get {
                return ResourceManager.GetString("UserRegisterCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
