//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtqanArchive.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtqanArchive.Localization.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun transfer balance must be greater than or equal {0}.
        /// </summary>
        public static string BalanceTransferLessThanLimitedBalance {
            get {
                return ResourceManager.GetString("BalanceTransferLessThanLimitedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book ticket transaction not found.
        /// </summary>
        public static string BookTicketTransactionNotFound {
            get {
                return ResourceManager.GetString("BookTicketTransactionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calculated balance not match with available balance.
        /// </summary>
        public static string CalculatedBalanceNotMatchWithAvailableBalance
        {
            get
            {
                return ResourceManager.GetString("CalculatedBalanceNotMatchWithAvailableBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم ايجاد الملف .
        /// </summary>
        public static string DirectoryNotFound
        {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category has no commision.
        /// </summary>
        public static string CategoryHasNoCommision {
            get {
                return ResourceManager.GetString("CategoryHasNoCommision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category image is required.
        /// </summary>
        public static string CategoryImageRequired {
            get {
                return ResourceManager.GetString("CategoryImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ticket status not allow cancellation.
        /// </summary>
        public static string CurrentTicketStatusNotAllowCancellation {
            get {
                return ResourceManager.GetString("CurrentTicketStatusNotAllowCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has pending transfer balance.
        /// </summary>
        public static string CustomerHasPendingBalanceTransfer {
            get {
                return ResourceManager.GetString("CustomerHasPendingBalanceTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer doesn&apos;t have portfolio with the specified currency.
        /// </summary>
        public static string CustomerNotHavePortfolio {
            get {
                return ResourceManager.GetString("CustomerNotHavePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be after or equal today.
        /// </summary>
        public static string DateMustBeAfterOrEqualToday {
            get {
                return ResourceManager.GetString("DateMustBeAfterOrEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime must be after now.
        /// </summary>
        public static string DateTimeMustBeAfterNow {
            get {
                return ResourceManager.GetString("DateTimeMustBeAfterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cancel attended ticket.
        /// </summary>
        public static string ErrorMsg_CanceledAttendedTicket {
            get {
                return ResourceManager.GetString("ErrorMsg_CanceledAttendedTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached to maximum pending events.
        /// </summary>
        public static string ErrorMsg_MaxPendingEvents {
            get {
                return ResourceManager.GetString("ErrorMsg_MaxPendingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket refund not allowed.
        /// </summary>
        public static string ErrorMsg_TicketNotAllowRefund {
            get {
                return ResourceManager.GetString("ErrorMsg_TicketNotAllowRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event cover image is required.
        /// </summary>
        public static string EventCoverImageRequired {
            get {
                return ResourceManager.GetString("EventCoverImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date required.
        /// </summary>
        public static string EventDateRequired {
            get {
                return ResourceManager.GetString("EventDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event from date required.
        /// </summary>
        public static string EventFromDateRequired {
            get {
                return ResourceManager.GetString("EventFromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event gallery is required.
        /// </summary>
        public static string EventGalleryRequired {
            get {
                return ResourceManager.GetString("EventGalleryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event already has available tickets.
        /// </summary>
        public static string EventHasAvailableTickets {
            get {
                return ResourceManager.GetString("EventHasAvailableTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available tickets.
        /// </summary>
        public static string EventNoAvailableTickets {
            get {
                return ResourceManager.GetString("EventNoAvailableTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event does not allow waiting list.
        /// </summary>
        public static string EventNotAllowWaitingList {
            get {
                return ResourceManager.GetString("EventNotAllowWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is not found.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not selected.
        /// </summary>
        public static string EventNotSelected {
            get {
                return ResourceManager.GetString("EventNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ticket class floor plan section required.
        /// </summary>
        public static string EventTicketClassFloorPlanSectionRequired {
            get {
                return ResourceManager.GetString("EventTicketClassFloorPlanSectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected ticket class is fully booked, Try booking different class.
        /// </summary>
        public static string EventTicketClassFullyBooked {
            get {
                return ResourceManager.GetString("EventTicketClassFullyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ticket class participants must be less than or equal number of floor plan section seats.
        /// </summary>
        public static string EventTicketClassMaxNoParticipantMustLessThanNoSectionSeats {
            get {
                return ResourceManager.GetString("EventTicketClassMaxNoParticipantMustLessThanNoSectionSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ticket class not found.
        /// </summary>
        public static string EventTicketClassNotFound {
            get {
                return ResourceManager.GetString("EventTicketClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets are more than available.
        /// </summary>
        public static string EventTicketsMoreThanAvailable {
            get {
                return ResourceManager.GetString("EventTicketsMoreThanAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event to date required.
        /// </summary>
        public static string EventToDateRequired {
            get {
                return ResourceManager.GetString("EventToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is expired..
        /// </summary>
        public static string ExpiredEvent {
            get {
                return ResourceManager.GetString("ExpiredEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket event is expired. ticket not allow to refund.
        /// </summary>
        public static string ExpiredTicketRefundNotAllow {
            get {
                return ResourceManager.GetString("ExpiredTicketRefundNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add to waiting list.
        /// </summary>
        public static string FailedToAddToWaitingList {
            get {
                return ResourceManager.GetString("FailedToAddToWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove user from waiting list.
        /// </summary>
        public static string FailedToRemoveFromWaitingList {
            get {
                return ResourceManager.GetString("FailedToRemoveFromWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field invalid value.
        /// </summary>
        public static string FieldInvalidValue {
            get {
                return ResourceManager.GetString("FieldInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must have one value at least.
        /// </summary>
        public static string FieldMustHaveOneValueAtLeast {
            get {
                return ResourceManager.GetString("FieldMustHaveOneValueAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed number must be geater than zero.
        /// </summary>
        public static string FiledMustBeMoreThanZero {
            get {
                return ResourceManager.GetString("FiledMustBeMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saving failed.
        /// </summary>
        public static string FileSavingFailed {
            get {
                return ResourceManager.GetString("FileSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date must be greater than or equal today.
        /// </summary>
        public static string FromDateBeGreaterThanOrEqualToday {
            get {
                return ResourceManager.GetString("FromDateBeGreaterThanOrEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect demand seat section.
        /// </summary>
        public static string IncorrectDemandSeatSection {
            get {
                return ResourceManager.GetString("IncorrectDemandSeatSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid financial accounts.
        /// </summary>
        public static string InvalidFinancialAccounts {
            get {
                return ResourceManager.GetString("InvalidFinancialAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not valid.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment method.
        /// </summary>
        public static string InvalidPaymentMethod {
            get {
                return ResourceManager.GetString("InvalidPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price or total price.
        /// </summary>
        public static string InvalidPriceOrTotalPrice {
            get {
                return ResourceManager.GetString("InvalidPriceOrTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some properties are not valid.
        /// </summary>
        public static string InvalidSomeProperties {
            get {
                return ResourceManager.GetString("InvalidSomeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ticket status.
        /// </summary>
        public static string InvalidTicketStatus {
            get {
                return ResourceManager.GetString("InvalidTicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ticket template file format. please upload file in pdf format.
        /// </summary>
        public static string InvalidTicketTemplateFileFormat {
            get {
                return ResourceManager.GetString("InvalidTicketTemplateFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserId.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice transaction not found.
        /// </summary>
        public static string InvoiceTransactionNotFound {
            get {
                return ResourceManager.GetString("InvoiceTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one event is found.
        /// </summary>
        public static string MoreThanOneEventFound {
            get {
                return ResourceManager.GetString("MoreThanOneEventFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status not in booked.
        /// </summary>
        public static string NotBookedTicketStatusNotAllowToAttend {
            get {
                return ResourceManager.GetString("NotBookedTicketStatusNotAllowToAttend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more tickets couldn&apos;t be refunded.
        /// </summary>
        public static string OneOrMoreTicketsCouldNotRefund {
            get {
                return ResourceManager.GetString("OneOrMoreTicketsCouldNotRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand Must Match &quot;&lt;=&quot;  &quot;&gt;=&quot;.
        /// </summary>
        public static string OperandMustMatch {
            get {
                return ResourceManager.GetString("OperandMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand Not Null Or Empty.
        /// </summary>
        public static string OperandNotNull {
            get {
                return ResourceManager.GetString("OperandNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand Value Must Be Greater Than Zero.
        /// </summary>
        public static string OperandValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("OperandValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is Not Exist.
        /// </summary>
        public static string OperatorNotFound {
            get {
                return ResourceManager.GetString("OperatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageNumber must be greater than 0.
        /// </summary>
        public static string PageNumberMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("PageNumberMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSize must be greater than 0.
        /// </summary>
        public static string PageSizeMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("PageSizeMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund multiple events tickets not allowed in one process.
        /// </summary>
        public static string RefundMultipleEventsNotAllowed {
            get {
                return ResourceManager.GetString("RefundMultipleEventsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request data is not in correct format.
        /// </summary>
        public static string RequestDataInCorrectFormat {
            get {
                return ResourceManager.GetString("RequestDataInCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type is required.
        /// </summary>
        public static string RequestTypeRequired {
            get {
                return ResourceManager.GetString("RequestTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not found.
        /// </summary>
        public static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected seat already booked. please select another one.
        /// </summary>
        public static string SeatAlreadyBooked {
            get {
                return ResourceManager.GetString("SeatAlreadyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat not found.
        /// </summary>
        public static string SeatNotFound {
            get {
                return ResourceManager.GetString("SeatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats fully booked.
        /// </summary>
        public static string SeatsFullyBooked {
            get {
                return ResourceManager.GetString("SeatsFullyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats not found.
        /// </summary>
        public static string SeatsNotFound {
            get {
                return ResourceManager.GetString("SeatsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client email required.
        /// </summary>
        public static string TicketClientEmailRequired {
            get {
                return ResourceManager.GetString("TicketClientEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client identity required.
        /// </summary>
        public static string TicketClientIdentityRequired {
            get {
                return ResourceManager.GetString("TicketClientIdentityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client mobile required.
        /// </summary>
        public static string TicketClientMobileRequired {
            get {
                return ResourceManager.GetString("TicketClientMobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name required.
        /// </summary>
        public static string TicketClientNameRequired {
            get {
                return ResourceManager.GetString("TicketClientNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client personal image required.
        /// </summary>
        public static string TicketClientPersonalImageRequired {
            get {
                return ResourceManager.GetString("TicketClientPersonalImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket cover image is required.
        /// </summary>
        public static string TicketCoverImageRequired {
            get {
                return ResourceManager.GetString("TicketCoverImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found.
        /// </summary>
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket price must not be less than zero.
        /// </summary>
        public static string TicketPriceMustNotBeLessThanZero {
            get {
                return ResourceManager.GetString("TicketPriceMustNotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject refund the ticket according to the refund policy.
        /// </summary>
        public static string TicketRefundPolicyReject {
            get {
                return ResourceManager.GetString("TicketRefundPolicyReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject refund the ticket because refund amount equal zero.
        /// </summary>
        public static string TicketRefundPriceReject {
            get {
                return ResourceManager.GetString("TicketRefundPriceReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket seat already booked.
        /// </summary>
        public static string TicketSeatAlreadyBooked {
            get {
                return ResourceManager.GetString("TicketSeatAlreadyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status id canceled.
        /// </summary>
        public static string TicketStatusCanceled {
            get {
                return ResourceManager.GetString("TicketStatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status id expired.
        /// </summary>
        public static string TicketStatusExpired {
            get {
                return ResourceManager.GetString("TicketStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status is not booked.
        /// </summary>
        public static string TicketStatusNotBooked {
            get {
                return ResourceManager.GetString("TicketStatusNotBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status id pending.
        /// </summary>
        public static string TicketStatusPending {
            get {
                return ResourceManager.GetString("TicketStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket template not found.
        /// </summary>
        public static string TicketTemplateNotFound {
            get {
                return ResourceManager.GetString("TicketTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date must be greater than or equal from date.
        /// </summary>
        public static string ToDateBeGreaterThanOrEqualFromDate {
            get {
                return ResourceManager.GetString("ToDateBeGreaterThanOrEqualFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date must be after from date.
        /// </summary>
        public static string ToDateMustBeAfterFromDate {
            get {
                return ResourceManager.GetString("ToDateMustBeAfterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To datetime must be after from datetime.
        /// </summary>
        public static string ToDateTimeMustBeAfterFromDateTime {
            get {
                return ResourceManager.GetString("ToDateTimeMustBeAfterFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required.
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is not approved.
        /// </summary>
        public static string TransactionNotApproved {
            get {
                return ResourceManager.GetString("TransactionNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction status pending.
        /// </summary>
        public static string TransactionStatusPending {
            get {
                return ResourceManager.GetString("TransactionStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already on the waiting list for this event.
        /// </summary>
        public static string UserAlreadyOnWaitingList {
            get {
                return ResourceManager.GetString("UserAlreadyOnWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user already reviewed this event.
        /// </summary>
        public static string UserAlreadyReviewedThisEvent {
            get {
                return ResourceManager.GetString("UserAlreadyReviewedThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not a customer.
        /// </summary>
        public static string UserNotCustomer {
            get {
                return ResourceManager.GetString("UserNotCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not on waiting list.
        /// </summary>
        public static string UserNotOnWaitingList {
            get {
                return ResourceManager.GetString("UserNotOnWaitingList", resourceCulture);
            }
        }
    }
}
